DROP TABLE IF EXISTS project_table;
 
CREATE TABLE PROJECT_TABLE
 (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  actions VARCHAR(250) DEFAULT NULL,
  completed Bool DEFAULT FALSE
);